theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag
title: Network Game Copier
description: A tool that allows users to copy their games over the local network.
show_downloads: true
social:
  name: Francisco Santos
  links: 
  - https://www.facebook.com/f.polac0
  - https://www.linkedin.com/in/francisco-santos-bb6054115/
  - https://github.com/francisco-polaco
